name = "centramind-social-meta"
main = "src/index.js"
compatibility_date = "2026-05-19"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "eternium.ai/*", zone_id = "2ccf9bd54040d93f2382875f2aa672d4" },
  { pattern = "www.eternium.ai/*", zone_id = "2ccf9bd54040d93f2382875f2aa672d4" }
]

[observability]
enabled = true
